### ISSUE TITLE
Spelling error on line 406 in DevelopmentStack.json

### ISSUE THREAD

**Issue by henryspivey** [unruledboy/DevelopmentStack#1]
Hello,
First of all, cool tree!

I wanted to let you know I found a spelling error on line 406. As of now it says:  "name": "Concetps",
I believe it should be changed to  "name": "Concepts",

Thanks,
Henry Spivey

**Comment by unruledboy** [comment]
hi,

you are right, that is a typo, thanks, we will fix it ASAP

**Comment by unruledboy** [comment]
fixed and updated. thanks, mate.

Do you want to be contributor?

**Comment by henryspivey** [comment]
Sure. What can I help you with?

**Comment by unruledboy** [comment]
Either a typo fix, or a new category/item, or completely change the structure, as long as it is a good idea.

And, welcome to the party! Cheers, mate.

**Comment by henryspivey** [comment]
Ok. I'll take a look at the project and see what I can contribute!

**Comment by unruledboy** [comment]
Thanks mate, feel free and enjoy.
